FROM python:3.6.4
ENV PYTHONUNBUFFERED 1

# Install requirement to compile messages
RUN apt-get update && apt-get install -y gettext libgettextpo-dev postgresql-client

# Creating working directory
RUN mkdir /source
WORKDIR /source

# Copying requirements
COPY . .
RUN pip install -r requirements.txt