version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - angular
      - django
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media
      - ./dist:/dist

  postgres:
    image: postgres:9.6
    volumes:
      - postgres_{{cookiecutter.project_name}}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={{cookiecutter.database_username}}
      - POSTGRES_PASSWORD={{cookiecutter.database_password}}
      - POSTGRES_DB={{cookiecutter.database_name}}
  
  django:
    image: {{cookiecutter.django_image_registry}}:{{cookiecutter.docker_image_tag}}
    command: ["docker/wait-for-postgres.sh", "postgres", "postgres", "postgres"]
    entrypoint: docker/entrypoint.sh
    environment:
      - DATABASE_URL=postgres://{{cookiecutter.database_username}}:{{cookiecutter.database_password}}@postgres:5432/{{cookiecutter.database_name}}
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./static:/source/static
      - ./media:/source/media

  angular:
    image: {{cookiecutter.angular_image_registry}}:{{cookiecutter.docker_image_tag}}
    command: bash -c "npm run build && cp -R dist/. tmp/"
    volumes:
      - ./dist:/source/tmp

volumes:
  postgres_{{cookiecutter.project_name}}: